name: video_editor
version: 3.0.0
description: |
 A flutter package for editing video with fully customizable UI.
 Supports crop, trim, rotation and cover selection.
 Provides commands to run in order to export the video or cover.
repository: https://github.com/LeGoffMael/video_editor

environment:
 sdk: ">=3.2.2 <4.0.0"
 flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.1 # update to `1.8.1` causes #79
  path_provider: ^2.1.5
  transparent_image: ^2.0.1 # show fade-in placeholder in thumbnails generation
  video_player: ^2.9.3
  video_thumbnail: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

screenshots:
  - description: 'Video editor demo'
    path: assets/demo_thumb.webp